# Generated by Django 3.1 on 2020-10-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201028_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
